# Generated by Django 4.1.3 on 2023-09-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='favorites',
        ),
    ]
