# Generated by Django 4.1.6 on 2023-09-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_interested',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
