# Generated by Django 4.1.3 on 2023-09-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_account_favorites'),
        ('offers', '0005_favorite_delete_image_remove_house_interested_users_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
