# Generated by Django 4.1.3 on 2023-09-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_favorite'),
        ('accounts', '0005_remove_account_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='offers.favorite'),
        ),
    ]
